var data=[ {
    'gender': 'Men',
    'productLocation': ' right corner of the Second floor',
    'productCategory': 'Apparel',
    'productId': 'p10137',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Black',
    'productType': 'Shirts',
    'productSize': 'XL',
    'image': '18TM1MQNLLLSWVNF1APT_Black.webp',
    'price': '129',
    'productFeatures': 'Regular, Removable collar, Button-up',
    'quantity': '1',
    'productTitle': "TravisMathew Men's Quinella Long Sleeve Golf Shirt",
    'brand': 'TravisMathew'
}, {
    'gender': 'Men',
    'productLocation': 'left corner of the store at the Second floor ',
    'productCategory': 'Apparel',
    'productId': 'p10138',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Black',
    'productType': 'Shirts',
    'productSize': 'XXL',
    'image': '21TM1MSTKSBTTNPLSMGA_Black.webp',
    'price': '124',
    'productFeatures': 'Regular, Light weight',
    'quantity': '1',
    'productTitle': "TravisMathew Men's High Stakes Button-Up Flannel Golf Shirt",
    'brand': 'TravisMathew'
}, {
    'gender': 'Men',
    'productLocation': 'last left corner of the store',
    'productCategory': 'Apparel',
    'productId': 'p10139',
    'isToprated': 'TRUE',
    'isBestSeller': 'TRUE',
    'colour': 'Cream',
    'productType': 'Pants',
    'productSize': 'Large',
    'image': '21KRMMCMMTR5PCKTSMPD_Sandy_Clay-1.webp',
    'price': '80',
    'productFeatures': 'Skinny, 5 pockets,Durable, bonded belt loops',
    'quantity': '29',
    'productTitle': "VRST Men's Limitless 5 Pocket Skinny Fit Pant",
    'brand': 'VRST'
}, {
    'gender': 'Men',
    'productLocation': 'last left corner of the store',
    'productCategory': 'Apparel',
    'productId': 'p10140',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'colour': 'Blue',
    'productType': 'Pants',
    'productSize': 'Large',
    'image': '21KRMMSLMFTPNTXXXMPD_DarkerBlue_Ardosia_Slate.webp',
    'price': '80',
    'productFeatures': 'activewear, Stretch fabric,Slim',
    'quantity': '17',
    'productTitle': "VRST Men's Limitless Slant Pocket Slim Fit Pants",
    'brand': 'VRST'
}, {
    'gender': 'Men',
    'productLocation': 'last left corner of the store',
    'productCategory': 'Apparel',
    'productId': 'p10141',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'colour': 'Brown',
    'productType': 'Pants',
    'productSize': 'Large',
    'image': '21KRMMTHLTCFTPNTXMPD_Delta_Brown.webp',
    'price': '80',
    'productFeatures': 'Athletic pant, Stretch-constructed,Bonded belt loops,athlete',
    'quantity': '59',
    'productTitle': "VRST Men's Limitless Slant Pocket Athletic Fit Pants",
    'brand': 'VRST'
}, {
    'gender': 'Men',
    'productLocation': 'last right corner of the store',
    'productCategory': 'Apparel',
    'productId': 'p10142',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Orange',
    'productType': 'Pants',
    'productSize': 'Medium',
    'image': '22KRMMSYPNTXXXXXXMPD_Orange.webp',
    'price': '40',
    'productFeatures': 'Relaxed, Two zippered back pockets,2-way stretch fabric',
    'quantity': '25',
    'productTitle': "VRST Men's Athletic Fit Easy Pant",
    'brand': 'VRST'
}, {
    'gender': 'Men',
    'productLocation': 'last right corner of the store',
    'productCategory': 'Apparel',
    'productId': 'p10143',
    'isToprated': 'TRUE',
    'isBestSeller': 'TRUE',
    'colour': 'Black',
    'productType': 'Pants',
    'productSize': 'Medium',
    'image': '20TM1MLGCYSP20XXXMGAAX_Black.webp',
    'price': '159',
    'productFeatures': 'Regular, Lightweight cotton, Stretch waistband',
    'quantity': '30',
    'productTitle': "TravisMathew Men's Legacy Denim Golf Pants",
    'brand': 'TravisMathew'
}, {
    'productLocation': ' Right corner on the Second Floor.',
    'productCategory': 'Apparel',
    'productId': 'p10144',
    'isToprated': 'TRUE',
    'isBestSeller': 'TRUE',
    'colour': 'Black',
    'productType': 'Backpacks',
    'productSize': 'Medium',
    'image': '20TM1MLGCYSP20XXXMGAAX_Black.webp',
    'price': '190',
    'productFeatures': 'Regular, Lightweight',
    'quantity': 'NaN',
    'productTitle': 'American Tourister',
    'brand': 'American Tourister'
}]



enumobj={}

enumobj["brand"] = data.map((item)=>item.brand)

console.log("brand",enumobj)