
var data = [{
    'productLocation': '3rd Floor, Aisle 8',
    'productCategory': 'Appliances',
    'productId': 'p10024',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'productType': 'Vacuum Cleaners',
    'productSize': '14kPa',
    'image': 'dyson-stick-vacuums-405863-01-64_1000.webp',
    'price': '499',
    'productFeatures': 'Cordless, Light weight',
    'quantity': '39',
    'productTitle': 'V12 Detect Slim Cordless Bagless Stick Vacuum Cleaner with Laser Illumination',
    'brand': 'Dyson',
    'colour': ''
}, {
    'productLocation': '3rd Floor, Aisle 8',
    'productCategory': 'Appliances',
    'productId': 'p10025',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'productType': 'Vacuum Cleaners',
    'productSize': '12kpa',
    'image': 'shark-stick-vacuums-iz142hd-64_1000.webp',
    'price': '349',
    'productFeatures': 'Cordless Stick',
    'quantity': '56',
    'productTitle': 'Pet Pro Cordless Stick Vacuum Cleaner',
    'brand': 'Shark',
    'colour': ''
}, {
    'productLocation': '3rd Floor, Aisle 8',
    'productCategory': 'Appliances',
    'productId': 'p10026',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'productType': 'Vacuum Cleaners',
    'productSize': '13kpa',
    'image': 'dyson-upright-vacuums-216034-01-64_1000.webp',
    'price': '349',
    'productFeatures': ' Upright',
    'quantity': '89',
    'productTitle': 'Slim Ball Animal Upright Vacuum Cleaner',
    'brand': 'Dyson',
    'colour': ''
}, {
    'productLocation': '3rd Floor, Aisle 8',
    'productCategory': 'Appliances',
    'productId': 'p10027',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'productType': 'Vacuum Cleaners',
    'productSize': '9kpa',
    'image': 'hoover-upright-vacuums-uh72625-64_1000.webp',
    'price': '199',
    'productFeatures': 'odor-absorbing carbon HEPA Filtration, Pet Hair',
    'quantity': '34',
    'productTitle': 'WindTunnel 3 Max Performance Pet Bagless Upright Vacuum Cleaner Machine with HEPA Media Filtration',
    'brand': 'Hoover',
    'colour': ''
}, {
    'productLocation': '3rd Floor, Aisle 8',
    'productCategory': 'Appliances',
    'productId': 'p10028',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'productType': 'Vacuum Cleaners',
    'productSize': '13kpa',
    'image': 'irobot-robotic-vacuums-i355020-64_1000.webp',
    'price': '349',
    'productFeatures': 'Full Indicator,Edge Cleaner,Low Battery Indicator,Pet Hair,Rechargeable,Rotating Brush',
    'quantity': '100',
    'productTitle': 'Roomba i3+ EVO (3550) Self-Emptying Robot Vacuum â€“ Now Clean By Room With Smart Mapping, Ideal For Pet Hair',
    'brand': 'iRobot',
    'colour': ''
}, {
    'productLocation': '3rd Floor, Aisle 8',
    'productCategory': 'Appliances',
    'productId': 'p10029',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'productType': 'Vacuum Cleaners',
    'productSize': '10kpa',
    'image': 'irobot-robotic-vacuums-i315020-64_1000.webp',
    'price': '229',
    'productFeatures': 'Edge Cleaner,Pet Hair,Rechargeable,Scheduling Capabilities,Wifi',
    'quantity': '167',
    'productTitle': 'Roomba i3 EVO (3150) Robot Vacuum - Now Clean by Room with Smart Mapping, Ideal for Pet Hair, Carpet and Hard Floor',
    'brand': 'iRobot',
    'colour': ''
}, {
    'productLocation': '3rd Floor, Aisle 1, Rack 8',
    'productCategory': 'Appliances',
    'productId': 'p10030',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'productType': 'Ovens',
    'productSize': '4L',
    'image': 'Oven_Roomtec_Combo21_rnhcan.png',
    'price': '1060',
    'productFeatures': '21-in-1 Countertop Convection, toaster,Air Fryer',
    'quantity': '19',
    'productTitle': 'Air Fryer Toaster Oven Combo, 21-in-1 Countertop Convection Ovens with 9 Accessories',
    'brand': 'Roomtec',
    'colour': ''
}, {
    'productLocation': '3rd Floor, Aisle 1, Rack 8',
    'productCategory': 'Appliances',
    'productId': 'p10031',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'productType': 'Ovens',
    'productSize': '4L',
    'image': 'Oven_Oster_1_euous8.jpg',
    'price': '500',
    'productFeatures': 'Countertop,Broiler, Convection',
    'quantity': '21',
    'productTitle': 'Silver Countertop Digital French Door Convection Oven',
    'brand': 'Oster',
    'colour': ''
}, {
    'productLocation': '3rd Floor, Aisle 1, Rack 8',
    'productCategory': 'Appliances',
    'productId': 'p10032',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'productType': 'Ovens',
    'productSize': '3L',
    'image': 'Oven_NuWave_Broiler_ckncfu.jpg',
    'price': '1320',
    'productFeatures': 'Toast, Broiler',
    'quantity': '30',
    'productTitle': "Crisp 'N Bake toaster ovens",
    'brand': 'NuWave',
    'colour': ''
}, {
    'productLocation': '3rd Floor, Aisle 1, Rack 8',
    'productCategory': 'Appliances',
    'productId': 'p10033',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'productType': 'Ovens',
    'productSize': '5L',
    'image': 'Oven_Fotile_1550Slice_v1k2jr.jpg',
    'price': '523',
    'productFeatures': 'Air Fry, Bake',
    'quantity': '12',
    'productTitle': '1550-Watt 6-Slice White Convection Steam Oven with Air Fryer and Food Dehydrator',
    'brand': 'Fotile',
    'colour': ''
}, {
    'productLocation': '3rd Floor, Aisle 1, Rack 8',
    'productCategory': 'Appliances',
    'productId': 'p10034',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'colour': 'White',
    'productType': 'Ovens',
    'productSize': '4L',
    'image': 'white-whirlpool-over-the-range-microwaves-wmh31017hw-64_1000.webp',
    'price': '228',
    'productFeatures': 'Electric Touch Control, Defrost,Turntable, Smart-Touch Cooking',
    'quantity': '50',
    'productTitle': '1.7 cu. Ft. Over the Range Microwave in White',
    'brand': 'Whirlpool'
}, {
    'productLocation': '3rd Floor, Aisle 1, Rack 8',
    'productCategory': 'Appliances',
    'productId': 'p10035',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'colour': 'Black',
    'productType': 'Ovens',
    'productSize': '6L',
    'image': 'stainless-steel-panasonic-countertop-microwaves-nn-sn96js-64_1000.webp',
    'price': '269',
    'productFeatures': 'Countertop,Broiler, Convection,Inverter,Smart Touch Cooking,Safety Lock,Timer,Turntable',
    'quantity': '65',
    'productTitle': '2.2 cu. ft. Countertop Microwave in Stainless Steel Built-in with Cyclonic Wave Inverter Technology and Sensor Cook',
    'brand': 'Panasonic'
}, {
    'productLocation': '3rd Floor, Aisle 1, Rack 8',
    'productCategory': 'Appliances',
    'productId': 'p10036',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Grey',
    'productType': 'Ovens',
    'productSize': '3L',
    'image': 'stainless-steel-kitchenaid-commercial-countertop-kmbd104gss-64_1000.webp',
    'price': '1999',
    'productFeatures': 'SmartTouch Cooking,Defrost,Auto Touch, push-button control,Reheating',
    'quantity': '100',
    'productTitle': '1.2 cu. ft. Under-Counter Microwave Drawer in Stainless Steel',
    'brand': 'KitchenAid'
}, {
    'productLocation': '3rd Floor, Aisle 1, Rack 8',
    'productCategory': 'Appliances',
    'productId': 'p10037',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'colour': 'Slate',
    'productType': 'Ovens',
    'productSize': '4L',
    'image': 'slate-ge-profile-over-the-range-microwaves-pvm9179eres-64_600.webp',
    'price': '538',
    'productFeatures': 'With Vent,Convection Oven,Turntable,Air Fryer',
    'quantity': '125',
    'productTitle': '1.7 Cu. Ft. Over the Range Microwave in Stainless Steel with Air Fry',
    'brand': 'GE'
}, {
    'productLocation': '3rd Floor, Aisle 1, Rack 8',
    'productCategory': 'Appliances',
    'productId': 'p10038',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'White ',
    'productType': 'Ovens',
    'productSize': '5L',
    'image': 'matte-white-cafe-over-the-range-microwaves-cvm517p4rw2-64_1000.webp',
    'price': '848',
    'productFeatures': 'With Vent,Convection Oven,Turntable,Air Fryer',
    'quantity': '200',
    'productTitle': '1.7 Cu. Ft. Over the Range Microwave in Matte White with Air Fry',
    'brand': 'Cafe'
}, {
    'productLocation': '3rd Floor, Aisle 1, Rack 8',
    'productCategory': 'Appliances',
    'productId': 'p10039',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'colour': 'Grey',
    'productType': 'Ovens',
    'productSize': '3L',
    'image': 'fingerprint-resistant-stainless-steel-samsung-over-the-range-microwaves-me11a7710ds-64_1000.webp',
    'price': '418',
    'productFeatures': 'Fingerprint Resistant,Removable Filter,Reheat,Wifi Control',
    'quantity': '50',
    'productTitle': '1.1 cu. ft. Smart SLIM Over-the-Range Microwave with Wi-Fi Voice Control in Fingerprint Resistant Stainless Steel',
    'brand': 'Samsung'
}, {
    'productLocation': '3rd Floor, Aisle 6',
    'productCategory': 'Appliances',
    'productId': 'p10040',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'White',
    'productType': 'Washing Machines',
    'productSize': '8.5Kg',
    'image': 'WM_Hotpoint_TopLoad2_f1yf9f.png',
    'price': '2002',
    'productFeatures': 'Top Load, Agitator',
    'quantity': '25',
    'productTitle': 'Hotpoint 3.8 cu. ft. White Top Load Washer with Agitator',
    'brand': 'Hotpoint'
}, {
    'productLocation': '3rd Floor, Aisle 6',
    'productCategory': 'Appliances',
    'productId': 'p10041',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'colour': 'Black ',
    'productType': 'Washing Machines',
    'productSize': '8.5Kg',
    'image': 'WM_LG_FrontLoadBlack_lsrjsf.jpg',
    'price': '724',
    'productFeatures': 'Front Load, Stackable',
    'quantity': '899',
    'productTitle': 'High Capacity High Efficiency Stackable Front Load Washer in White',
    'brand': 'LG Electronics'
}, {
    'productLocation': '3rd Floor, Aisle 6',
    'productCategory': 'Appliances',
    'productId': 'p10042',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'colour': 'Black',
    'productType': 'Washing Machines',
    'productSize': '8Kg',
    'image': 'WM_Samsung_TopLoadBlack_cg6hkr.png',
    'price': '844',
    'productFeatures': 'Top Load, Agitator',
    'quantity': '899',
    'productTitle': 'High-Efficiency Black Top Load Washer with Agitator',
    'brand': 'G.E.'
}, {
    'productLocation': '3rd Floor, Aisle 6',
    'productCategory': 'Appliances',
    'productId': 'p10043',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'colour': 'White',
    'productType': 'Washing Machines',
    'productSize': '9Kg',
    'image': 'WM_Samsung_TopLoadWhite_jejo9f.jpg',
    'price': '515',
    'productFeatures': 'Top Load, Agitator',
    'quantity': '25',
    'productTitle': 'Top Load Washer with Agitator',
    'brand': 'Samsung'
}, {
    'productLocation': '3rd Floor, Aisle 6',
    'productCategory': 'Appliances',
    'productId': 'p10044',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'colour': 'Black',
    'productType': 'Washing Machines',
    'productSize': '9kg',
    'image': 'chrome-shadow-whirlpool-front-load-washers-wfw862chc-64_600.jpg',
    'price': '1484',
    'productFeatures': 'Door Window End-Of-Cycle Signal,Add Garment ',
    'quantity': '200',
    'productTitle': '4.3 cu. ft. High Efficiency Chrome Shadow Front Load Washing Machine with Load & Go XL Dispenser',
    'brand': 'Whirlpool'
}, {
    'productLocation': '3rd Floor, Aisle 6',
    'productCategory': 'Appliances',
    'productId': 'p10045',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'White',
    'productType': 'Washing Machines',
    'productSize': '8kg',
    'image': 'costway-front-load-washers-ep24640us-64_1000.webp',
    'price': '267',
    'productFeatures': 'Input power of Spin: 220-Watt package includes',
    'quantity': '100',
    'productTitle': 'White Full-Automatic Laundry Washing Machine',
    'brand': 'Costway'
}, {
    'productLocation': '3rd Floor, Aisle 6',
    'productCategory': 'Appliances',
    'productId': 'p10046',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'colour': 'White',
    'productType': 'Washing Machines',
    'productSize': '6.5Kg',
    'image': 'WM_LG_FrontLoadLG_tsczkh.jpg',
    'price': '724',
    'productFeatures': 'Front Load, Stackable',
    'quantity': '899',
    'productTitle': 'High Efficiency Stackable Front Load Washer in White',
    'brand': 'LG Electronics'
}, {
    'productLocation': '3rd Floor, Aisle 6',
    'productCategory': 'Appliances',
    'productId': 'p10047',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'colour': 'White',
    'productType': 'Washing Machines',
    'productSize': '9kg',
    'image': 'white-lg-electronics-front-load-washers-wm3400cw-64_1000.webp',
    'price': '698',
    'productFeatures': 'Advanced Vibration ControlDoor Window',
    'quantity': '350',
    'productTitle': '4.5 cu. ft. Large Capacity High Efficiency Stackable Front Load Washer in White',
    'brand': 'LG Electronics'
}, {
    'productLocation': '3rd Floor, Aisle 6',
    'productCategory': 'Appliances',
    'productId': 'p10048',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Black',
    'productType': 'Washing Machines',
    'productSize': '9Kg',
    'image': 'WM_Samsung_TopLoadBlack_cg6hkr.png',
    'price': '844',
    'productFeatures': 'Top Load, Agitator',
    'quantity': '899',
    'productTitle': 'High-Efficiency Black Top Load Washer with Agitator',
    'brand': 'Samsung'
}, {
    'productLocation': '3rd Floor, Aisle 6',
    'productCategory': 'Appliances',
    'productId': 'p10049',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Grey',
    'productType': 'Washing Machines',
    'productSize': '9kg',
    'image': 'platinum-samsung-front-load-washers-wf45b6300ap-64_1000.webp',
    'price': '1028',
    'productFeatures': 'Wi-Fi EnabledAdvanced Vibration ControlWater Heater',
    'quantity': '38',
    'productTitle': '4.5 cu. ft. Smart High-Efficiency Front Load Washer with Super Speed in Platinum',
    'brand': 'Samsung'
}, {
    'productLocation': '2nd Floor, Aisle 2',
    'productCategory': 'Appliances',
    'productId': 'p10050',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'colour': 'Black',
    'productType': 'Refrigerators',
    'productSize': '742L',
    'image': 'refblack.webp',
    'price': '2608',
    'productFeatures': 'Water Dispenser,French Door',
    'quantity': '150',
    'productTitle': '26 cu. ft. French Door Smart Refrigerator with Ice and Water Dispenser in PrintProof Black Stainless Steel',
    'brand': 'LG Electronics'
}, {
    'productLocation': '2nd Floor, Aisle 2',
    'productCategory': 'Appliances',
    'productId': 'p10051',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Black',
    'productType': 'Refrigerators',
    'productSize': '696L',
    'image': 'fingerprint-resistant-stainless-steel-whirlpool-side-by-side-refrigerators-wrs325sdhz-64_1000.webp',
    'price': '1298',
    'productFeatures': 'Side - Side Door, Crushed Ice,Cubed Ice,Finger Print Resistant',
    'quantity': '250',
    'productTitle': '24.6 cu. ft. Side by Side Refrigerator in Fingerprint Resistant Stainless Steel',
    'brand': 'Whirlpool'
}, {
    'productLocation': '2nd Floor, Aisle 2',
    'productCategory': 'Appliances',
    'productId': 'p10052',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'colour': 'Grey',
    'productType': 'Refrigerators',
    'productSize': '764L',
    'image': 'printproof-stainless-steel-lg-electronics-french-door-refrigerators-lrfgc2706s-64_600.webp',
    'price': '2198',
    'productFeatures': 'Smart InstaView,3 Door, Ice Maker,Water Dispenser',
    'quantity': '90',
    'productTitle': '27 cu. ft. Smart InstaView Counter Depth MAX French Door Refrigerator with Internal Water in PrintProof Stainless Steel',
    'brand': 'LG Electronics'
}, {
    'productLocation': '2nd Floor, Aisle 2',
    'productCategory': 'Appliances',
    'productId': 'p10053',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'colour': 'White',
    'productType': 'Refrigerators',
    'productSize': '775L',
    'image': 'fingerprint-resistant-stainless-steel-samsung-side-by-side-refrigerators-rs27t5200sr-64_600.webp',
    'price': '1398',
    'productFeatures': 'Side - Side Door, Finger Print Resistant, Water Dispenser',
    'quantity': '100',
    'productTitle': '36 in. 27.4 cu. ft. Side by Side Refrigerator in Fingerprint-Resistant Stainless Steel, Standard Depth',
    'brand': 'Samsung'
}, {
    'productLocation': '2nd Floor, Aisle 2',
    'productCategory': 'Appliances',
    'productId': 'p10054',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Grey',
    'productType': 'Refrigerators',
    'productSize': '792L',
    'image': 'fingerprint-resistant-stainless-steel-samsung-french-door-refrigerators-rf28r7201sr-64_1000.webp',
    'price': '2398',
    'productFeatures': 'Water Dispenser,4-Door,Automatic Ice Level Control,Finger Print Resistant',
    'quantity': '155',
    'productTitle': '28 cu. ft. 4-Door French Door Smart Refrigerator in Fingerprint Resistant Stainless Steel, Standard Depth',
    'brand': 'Samsung'
}, {
    'productLocation': '2nd Floor, Aisle 2',
    'productCategory': 'Appliances',
    'productId': 'p10055',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'colour': 'Grey',
    'productType': 'Refrigerators',
    'productSize': '538L',
    'image': 'fingerprint-resistant-stainless-finish-whirlpool-french-door-refrigerators-wrqa59cnkz-64_1000.webp',
    'price': '2599',
    'productFeatures': 'Finger Print Resistant,Single Ice Maker,4-Door , French Door',
    'quantity': '80',
    'productTitle': '36 in. 19.4 cu. ft. 4-Door French Door Refrigerator in Fingerprint Resistant Stainless Steel, Counter Depth',
    'brand': 'Whirlpool'
}, {
    'productLocation': '2nd Floor, Aisle 2',
    'productCategory': 'Appliances',
    'productId': 'p10056',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'colour': 'Grey',
    'productType': 'Refrigerators',
    'productSize': '464L',
    'image': 'fingerprint-resistant-stainless-steel-haier-french-door-refrigerators-qhe16hypfs-64_1000.webp',
    'price': '1799',
    'productFeatures': 'Quad French Door, Without Ice Maker,4-Door',
    'quantity': '200',
    'productTitle': '16.4 cu. ft. Quad French Door Freezer Refrigerator in Fingerprint Resistant Stainless Steel',
    'brand': 'Haier'
}, {
    'productLocation': '2nd Floor, Aisle 2',
    'productCategory': 'Appliances',
    'productId': 'p10057',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Black ',
    'productType': 'Refrigerators',
    'productSize': '693L',
    'image': 'fingerprint-resistant-stainless-steel-whirlpool-french-door-refrigerators-wrx735sdhz-64_1000.webp',
    'price': '2999',
    'productFeatures': 'French Door,Finger Print resistant,Water Dispenser, Ice Dispenser',
    'quantity': '196',
    'productTitle': '24.5 cu. ft. French Door Refrigerator in Fingerprint Resistant Stainless Steel',
    'brand': 'Whirlpool'
}, {
    'productLocation': '2nd Floor, Aisle 2',
    'productCategory': 'Appliances',
    'productId': 'p10058',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Grey',
    'productType': 'Refrigerators',
    'productSize': '198L',
    'image': 'platinum-silver-lg-electronics-top-freezer-refrigerators-lrtnc0705v-64_1000.webp',
    'price': '584',
    'productFeatures': 'Top Mount, No dispenser,Manual Ice Tray ',
    'quantity': '200',
    'productTitle': '21.87 in. W 7 cu. ft. Top-Mount Refrigerator w/ LED Lighting and Inverter Compressor in Platinum Silver,ENERGY STAR',
    'brand': 'LG Electronics'
}, {
    'productLocation': '2nd Floor, Aisle 2',
    'productCategory': 'Appliances',
    'productId': 'p10059',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'colour': 'White',
    'productType': 'Refrigerators',
    'productSize': '580L',
    'image': 'white-frigidaire-top-freezer-refrigerators-frtd2021aw-64_1000.webp',
    'price': '678',
    'productFeatures': '2-Door, No Water Dispenser, without ice maker',
    'quantity': '175',
    'productTitle': '20.5 cu. ft. Top Freezer Refrigerator in White',
    'brand': 'Frigidaire'
}, {
    'productLocation': '2nd Floor, Aisle 5',
    'productCategory': 'Appliances',
    'productId': 'p10060',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'productType': 'Televisions',
    'productSize': '32in',
    'image': 'TV_RealMe_Smart3_ib6ess.jpg',
    'price': '1020',
    'productFeatures': 'LED, HDTV',
    'quantity': '899',
    'productTitle': 'Series Class LED 720P 1366 x 768 Widescreen HDTV Television',
    'brand': 'RealMe',
    'colour': ''
}, {
    'productLocation': '2nd Floor, Aisle 5',
    'productCategory': 'Appliances',
    'productId': 'p10061',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'productType': 'Televisions',
    'productSize': '64in',
    'image': 'naxa-flat-screen-tvs-nt-1600-64_1000.webp',
    'price': '1020',
    'productFeatures': 'LED, HDTV',
    'quantity': '899',
    'productTitle': 'OLED UltraWide Android TV',
    'brand': 'Samsung',
    'colour': ''
}, {
    'productLocation': '2nd Floor, Aisle 5',
    'productCategory': 'Appliances',
    'productId': 'p10062',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'productType': 'Televisions',
    'productSize': '14in',
    'image': 'TV_OnePlus_HDTV2_arclyc.jpg',
    'price': '600',
    'productFeatures': 'LED, HDTV',
    'quantity': '899',
    'productTitle': 'Vivid Plus Display, HDR+ Television',
    'brand': 'OnePlus',
    'colour': ''
}, {
    'productLocation': '2nd Floor, Aisle 5',
    'productCategory': 'Appliances',
    'productId': 'p10063',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'productType': 'Televisions',
    'productSize': '32in',
    'image': 'TV_Nokia_OLED_wijway.jpg',
    'price': '600',
    'productFeatures': 'LED, 4KTV',
    'quantity': '899',
    'productTitle': '4K OLED 55 Inch HDTV',
    'brand': 'Nokia',
    'colour': ''
}, {
    'productLocation': '2nd Floor, Aisle 5',
    'productCategory': 'Appliances',
    'productId': 'p10064',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'productType': 'Televisions',
    'productSize': '64in',
    'image': 'TV_LG_SmartAI_n7dzsq.jpg',
    'price': '600',
    'productFeatures': 'LED, 4KTV',
    'quantity': '899',
    'productTitle': 'UltraWide, SmartAI LED HDTV',
    'brand': 'LG Electronics',
    'colour': ''
}, {
    'productLocation': '2nd Floor, Aisle 5',
    'productCategory': 'Appliances',
    'productId': 'p10065',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'productType': 'Televisions',
    'productSize': '40in',
    'image': 'naxa-flat-screen-tvs-ntd-4050-64_1000.webp',
    'price': '249',
    'productFeatures': 'LED, HDTV',
    'quantity': '500',
    'productTitle': '40 in. Series Widescreen LED with 1080P 1920 x 1080 Resolution HDTV with DVD Player P',
    'brand': 'Naxa',
    'colour': ''
}, {
    'productLocation': '2nd Floor, Aisle 5',
    'productCategory': 'Appliances',
    'productId': 'p10066',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'productType': 'Televisions',
    'productSize': '14in',
    'image': 'trexonic-flat-screen-tvs-985110646m-64_1000.webp',
    'price': '118',
    'productFeatures': 'LED, HDTV, HDMI, SD, MMC, USB, VGA',
    'quantity': '300',
    'productTitle': 'Portable Screen Size Class 14 in. Rechargeable LED HDTV',
    'brand': 'Trexonic',
    'colour': ''
}, {
    'productLocation': '2nd Floor, Aisle 5',
    'productCategory': 'Appliances',
    'productId': 'p10067',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'productType': 'Televisions',
    'productSize': '25in',
    'image': 'naxa-flat-screen-tvs-nt-2500-64_1000.webp',
    'price': '139',
    'productFeatures': 'LED , HDTV',
    'quantity': '227',
    'productTitle': '25 in. Class LED Widescreen 1920 x 1080 Full HDTV Television with Car Cord',
    'brand': 'Naxa',
    'colour': ''
}, {
    'productLocation': '2nd Floor, Aisle 5',
    'productCategory': 'Appliances',
    'productId': 'p10068',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'productType': 'Televisions',
    'productSize': '14in',
    'image': 'trexonic-flat-screen-tvs-985115778m-64_1000.webp',
    'price': '133',
    'productFeatures': 'LED 1080p, Rechargeable Charger',
    'quantity': '135',
    'productTitle': '14 in. LED 1080p Portable Rechargeable TV',
    'brand': 'Trexonic',
    'colour': ''
}, {
    'productLocation': '2nd Floor, Aisle 5',
    'productCategory': 'Appliances',
    'productId': 'p10069',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'productType': 'Televisions',
    'productSize': '16in',
    'image': 'naxa-flat-screen-tvs-nt-1600-64_1000.webp',
    'price': '142',
    'productFeatures': 'LCD, HDTV',
    'quantity': '245',
    'productTitle': '16 in. LCD Series Rechargeable HDTV1366 x 768 Resolution and DC Car Cord',
    'brand': 'Naxa',
    'colour': ''
}, {
    'gender': 'Women',
    'productLocation': 'left corner of the store on the ground floor',
    'productCategory': 'Apparel',
    'productId': 'p10079',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Orange',
    'productType': 'Shirts',
    'productSize': 'Small',
    'image': '22JLOWCLBBBLMSHLNAPT_orange.webp',
    'price': '45',
    'productFeatures': 'Semi-relaxed, long sleeves',
    'quantity': '499',
    'productTitle': "CALIA Women's Bubble Mesh Long Sleeve Tee",
    'brand': 'Calia'
}, {
    'gender': 'Women',
    'productLocation': 'left corner of the store on the ground floor',
    'productCategory': 'Apparel',
    'productId': 'p10080',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Pink',
    'productType': 'Shirts',
    'productSize': 'Small',
    'image': '16UARWTWSTTCHCRWXAPT_pink.webp',
    'price': '25',
    'productFeatures': 'loose, short sleeves, Anti-microbial odor resistance, 4-way stretch material',
    'quantity': '500',
    'productTitle': "Under Armour Women's Tech Twist T-Shirt",
    'brand': 'Under Armour'
}, {
    'gender': 'Women',
    'productLocation': 'left corner of the store on the ground floor',
    'productCategory': 'Apparel',
    'productId': 'p10081',
    'isToprated': 'TRUE',
    'isBestSeller': 'TRUE',
    'colour': 'Purple',
    'productType': 'Shirts',
    'productSize': 'Small',
    'image': '22NIKWLGNDTXXXXXXAPT_purple.webp',
    'price': '30',
    'productFeatures': 'standard, short sleeves, crew neck ,dri',
    'quantity': '350',
    'productTitle': "Nike Women's Dri-FIT Legend T-Shirt",
    'brand': 'Nike'
}, {
    'gender': 'Women',
    'productLocation': 'left corner of the store on the ground floor',
    'productCategory': 'Apparel',
    'productId': 'p10082',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Red',
    'productType': 'Shirts',
    'productSize': 'Small',
    'image': '22ADIWSSSPCDYDPLPAPT_red.webp',
    'price': '60',
    'productFeatures': 'regular, collared, short sleeves',
    'quantity': '200',
    'productTitle': "adidas Women's Space-Dyed Golf Polo",
    'brand': 'Adidas'
}, {
    'gender': 'Women',
    'productLocation': 'right corner of the store on the ground floor.',
    'productCategory': 'Apparel',
    'productId': 'p10083',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Black',
    'productType': 'Shirts',
    'productSize': 'Medium',
    'image': '16UARWTWSTTCHCRWXAPT_black.webp',
    'price': '25',
    'productFeatures': 'loose,4-way stretch material , Anti-microbial odor resistance,short sleeves',
    'quantity': '400',
    'productTitle': "Under Armour Women's Tech Twist T-Shirt",
    'brand': 'Under Armour'
}, {
    'gender': 'Women',
    'productLocation': 'right corner of the store on the ground floor.',
    'productCategory': 'Apparel',
    'productId': 'p10084',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'colour': 'Blue',
    'productType': 'Shirts',
    'productSize': 'Medium',
    'image': '22NIKWLGNDTXXXXXXAPT_blue.webp',
    'price': '30',
    'productFeatures': 'standard, short sleeves, crew neck ,dri',
    'quantity': '300',
    'productTitle': "Nike Women's Dri-FIT Legend T-Shirt",
    'brand': 'Nike'
}, {
    'gender': 'Women',
    'productLocation': 'right corner of the store on the ground floor.',
    'productCategory': 'Apparel',
    'productId': 'p10085',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'colour': 'Yellow',
    'productType': 'Shirts',
    'productSize': 'Medium',
    'image': '17UARWNWTCH12ZPTWAPT_yellow.webp',
    'price': '45',
    'productFeatures': 'half zip closure, anti-microbial odor resistance,full sleeves,light weight',
    'quantity': '326',
    'productTitle': "Under Armour Women's Tech Twist-Print Half Zip Long Sleeve Shirt",
    'brand': 'Under Armour'
}, {
    'gender': 'Women',
    'productLocation': 'right corner of the store on the ground floor.',
    'productCategory': 'Apparel',
    'productId': 'p10086',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Grey',
    'productType': 'Shirts',
    'productSize': 'Medium',
    'image': '22JLOWCLVRYDYRLXDAPT_grey.webp',
    'price': '35',
    'productFeatures': 'relaxed, short sleeves, crew neck',
    'quantity': '426',
    'productTitle': "CALIA Women's Everyday Relaxed Tee",
    'brand': 'Calia'
}, {
    'gender': 'Women',
    'productLocation': 'center of the store on the ground floor',
    'productCategory': 'Apparel',
    'productId': 'p10087',
    'isToprated': 'TRUE',
    'isBestSeller': 'TRUE',
    'colour': 'Blue',
    'productType': 'Shirts',
    'productSize': 'Large',
    'image': '17UARWNWTCH12ZPTWAPT_navyblue.webp',
    'price': '45',
    'productFeatures': 'half zip closure, anti-microbial odor resistance,full sleeves,light weight',
    'quantity': '348',
    'productTitle': "Under Armour Women's Tech Twist-Print Half Zip Long Sleeve Shirt",
    'brand': 'Under Armour'
}, {
    'gender': 'Women',
    'productLocation': 'center of the store on the ground floor',
    'productCategory': 'Apparel',
    'productId': 'p10088',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'White',
    'productType': 'Shirts',
    'productSize': 'Large',
    'image': '20LHAWCRPQSLVLSSPAPT_White.webp',
    'price': '40',
    'productFeatures': 'relgular, sleevless,self collar',
    'quantity': '140',
    'productTitle': "Lady Hagen Women's Core Pique Sleeveless Golf Polo",
    'brand': 'Lady Hagen'
}, {
    'gender': 'Women',
    'productLocation': 'center of the store on the ground floor',
    'productCategory': 'Apparel',
    'productId': 'p10104',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'colour': 'White',
    'productType': 'Shirts',
    'productSize': 'Large',
    'image': '22JLOWCLVRYDYRLXDAPT_white.webp',
    'price': '35',
    'productFeatures': 'relaxed, short sleeves, crew neck,t-shirt',
    'quantity': '90',
    'productTitle': "CALIA Women's Everyday Relaxed Tee",
    'brand': 'Calia'
}, {
    'gender': 'Women',
    'productLocation': 'center of the store on the ground floor',
    'productCategory': 'Apparel',
    'productId': 'p10105',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'colour': 'Lavender',
    'productType': 'Shirts',
    'productSize': 'Large',
    'image': '22TNOGGSSGRPHCTXXAPT_lavender.webp',
    'price': '20',
    'productFeatures': 'regular,short sleeves,crew neck',
    'quantity': '70',
    'productTitle': "The North Face Girls' Short Sleeve Graphic T-Shirt",
    'brand': 'North Face'
}, {
    'gender': 'Women',
    'productLocation': 'left corner of the second floor.',
    'productCategory': 'Apparel',
    'productId': 'p10106',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Green',
    'productType': 'Shirts',
    'productSize': 'XL',
    'image': '22TNOGGSSGRPHCTXXAPT_green.webp',
    'price': '20',
    'productFeatures': 'regular,short sleeves,crew neck',
    'quantity': '55',
    'productTitle': "The North Face Girls' Short Sleeve Graphic T-Shirt",
    'brand': 'North Face'
}, {
    'gender': 'Women',
    'productLocation': 'left corner of the second floor.',
    'productCategory': 'Apparel',
    'productId': 'p10107',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'colour': 'Pink',
    'productType': 'Shirts',
    'productSize': 'XL',
    'image': '20LHAWCRPQSLVLSSPAPT_pink.webp',
    'price': '40',
    'productFeatures': 'relgular, sleevless,self collar,t-shirt',
    'quantity': '51',
    'productTitle': "Lady Hagen Women's Core Pique Sleeveless Golf Polo",
    'brand': 'Lady Hagen'
}, {
    'gender': 'Women',
    'productLocation': 'left corner of the second floor.',
    'productCategory': 'Apparel',
    'productId': 'p10108',
    'isToprated': 'TRUE',
    'isBestSeller': 'TRUE',
    'colour': 'Green',
    'productType': 'Shirts',
    'productSize': 'XL',
    'image': '22CA2WPFFSLVPLXXXWGA_green.webp',
    'price': '65',
    'productFeatures': 'regular, collared, short sleeve',
    'quantity': '64',
    'productTitle': "CALIA Women's Golf Puff Sleeve Polo",
    'brand': 'Calia'
}, {
    'gender': 'Women',
    'productLocation': 'left corner of the second floor.',
    'productCategory': 'Apparel',
    'productId': 'p10109',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'colour': 'Black',
    'productType': 'Shirts',
    'productSize': 'XL',
    'image': '22JLOWCLVRYDYRLXDAPT_black.webp',
    'price': '35',
    'productFeatures': 'relaxed, short sleeves, crew neck',
    'quantity': '90',
    'productTitle': "CALIA Women's Everyday Relaxed Tee",
    'brand': 'Calia'
}, {
    'gender': 'Women',
    'productLocation': 'left corner of the second floor.',
    'productCategory': 'Apparel',
    'productId': 'p10145',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Black',
    'productType': 'Shirts',
    'productSize': 'XL',
    'image': '22JLOWCLVRYDYRLXDAPT_black.webp',
    'price': '35',
    'productFeatures': 'relaxed, short sleeves, crew neck ',
    'quantity': '2',
    'productTitle': "LEVI'S Women's Everyday Relaxed Tee",
    'brand': "Levi's"
}, {
    'gender': 'Women',
    'productLocation': 'center of  the second floor',
    'productCategory': 'Apparel',
    'productId': 'p10110',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'colour': 'Green',
    'productType': 'Pants',
    'productSize': 'Medium',
    'image': '22PRAWWSNCHSLMPNTWOA_Green.webp',
    'price': '95',
    'productFeatures': 'High rise, Button closure, Continuous waistband construction',
    'quantity': '29',
    'productTitle': "prAna Women's Sancho Slim Pants",
    'brand': 'prAna'
}, {
    'gender': 'Women',
    'productLocation': 'right corner of the ground floor.',
    'productCategory': 'Apparel',
    'productId': 'p10111',
    'isToprated': 'TRUE',
    'isBestSeller': 'TRUE',
    'colour': 'Brown',
    'productType': 'Pants',
    'productSize': 'Large',
    'image': '22MHAWWDYNMLNDHGHWOA_Brown.webp',
    'price': '90',
    'productFeatures': 'High rise, Button closure, Continuous waistband construction',
    'quantity': '9',
    'productTitle': "Mountain Hardwear Women's Dynama Lined High Rise Pants",
    'brand': 'Mountain Hardwear'
}, {
    'gender': 'Women',
    'productLocation': 'center of  the second floor',
    'productCategory': 'Apparel',
    'productId': 'p10112',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'colour': 'Black',
    'productType': 'Pants',
    'productSize': 'Medium',
    'image': '17CMBWNYTMCSLPLLNAPB_Black.webp',
    'price': '50',
    'productFeatures': 'Active, Comfort stretch fabric',
    'quantity': '300',
    'productTitle': "Columbia Women's Anytime Casual Pull On Pants",
    'brand': 'Columbia'
}, {
    'gender': 'Women',
    'productLocation': 'right corner of the ground floor.',
    'productCategory': 'Apparel',
    'productId': 'p10113',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'colour': 'Grey',
    'productType': 'Pants',
    'productSize': 'Large',
    'image': '16CMBWSTRDYTRLRLLAPB_Grey.jpg',
    'price': '60',
    'productFeatures': 'Active, Articulated knees',
    'quantity': '780',
    'productTitle': "Columbia Women's Saturday Trail Roll-Up Pants",
    'brand': 'Columbia'
}, {
    'gender': 'Women',
    'productLocation': 'center of  the second floor',
    'productCategory': 'Apparel',
    'productId': 'p10114',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Green',
    'productType': 'Pants',
    'productSize': 'Medium',
    'image': '19CMBWWBNHDSTRTCHAPB_Green.webp',
    'price': '60',
    'productFeatures': 'Modern Classic/Regular, Lightweight, stretchy cotton-blend material',
    'quantity': '4',
    'productTitle': "Columbia Women's PFG Bonehead Stretch Pants",
    'brand': 'Columbia'
}, {
    'gender': 'Women',
    'productLocation': 'right corner of the ground floor.',
    'productCategory': 'Apparel',
    'productId': 'p10115',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'colour': 'Blue',
    'productType': 'Pants',
    'productSize': 'Large',
    'image': '22CMBWSLCKWTRFRNCAOT_Blue.webp',
    'price': '55',
    'productFeatures': 'Comfort stretch fabric, Regular',
    'quantity': '1',
    'productTitle': "Columbia Women's Slack Water French Terry Jogger",
    'brand': 'Columbia'
}, {
    'gender': 'Women',
    'productLocation': 'center of  the second floor',
    'productCategory': 'Apparel',
    'productId': 'p10116',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'colour': 'Pink',
    'productType': 'Pants',
    'productSize': 'Medium',
    'image': '22CMBWSLCKWTRFRNCAOT_Tiki_Pink.webp',
    'price': '55',
    'productFeatures': 'Regular,Elastic waistband , cuffs, Drawcord waist',
    'quantity': '19',
    'productTitle': "Columbia Women's Slack Water French Terry Jogger",
    'brand': 'Columbia'
}, {
    'gender': 'Women',
    'productLocation': 'right corner of the second floor.',
    'productCategory': 'Apparel',
    'productId': 'p10118',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Green',
    'productType': 'Pants',
    'productSize': 'Small',
    'image': '22ROXWNDLSSDZPNTXOBR_Spruce_Green.webp',
    'price': '50',
    'productFeatures': 'Regular,Printed, viscose, Elastic waistband',
    'quantity': '29',
    'productTitle': "Roxy Women's Endless Daze Pants",
    'brand': 'Roxy'
}, {
    'gender': 'Women',
    'productLocation': 'right corner of the second floor.',
    'productCategory': 'Apparel',
    'productId': 'p10119',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'colour': 'White',
    'productType': 'Pants',
    'productSize': 'Small',
    'image': '22ADIWLLSZNFLCPNTAPB_White.webp',
    'price': '29',
    'productFeatures': 'Loose,Drawcord elastic waist',
    'quantity': '59',
    'productTitle': "adidas Women's Sportswear ALL SZN Fleece Pants",
    'brand': 'Adidas'
}, {
    'gender': 'Women',
    'productLocation': 'right corner of the ground floor.',
    'productCategory': 'Apparel',
    'productId': 'p10120',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Pink',
    'productType': 'Pants',
    'productSize': 'Large',
    'image': '21ROXWCMFYPLCPNTXOBR_Pink.webp',
    'price': '45',
    'productFeatures': 'High waist,Elasticized waistband,Slight ruffle leg cuffs',
    'quantity': '16',
    'productTitle': "Roxy Women's Comfy Place Pants",
    'brand': 'Roxy'
}, {
    'gender': 'Women',
    'productLocation': 'right corner of the second floor.',
    'productCategory': 'Apparel',
    'productId': 'p10121',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Cream',
    'productType': 'Pants',
    'productSize': 'Small',
    'image': '20ROXWCNSDHGHWSTDOBR_Cream.webp',
    'price': '50',
    'productFeatures': 'cotton yarn-dyed fabric, Elasticized waistband',
    'quantity': '30',
    'productTitle': "Roxy Women's Oceanside High Waisted Flare Beach Pants",
    'brand': 'Roxy'
}, {
    'gender': 'Men',
    'productLocation': 'right corner of the first floor',
    'productCategory': 'Apparel',
    'productId': 'p10122',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'colour': 'White',
    'productType': 'Shirts',
    'productSize': 'Large',
    'image': '21WHGMP11JSMNPRNTAPT_Agave_Crisp_Wht_Monu_Grey.webp',
    'price': '10',
    'productFeatures': 'Regular short sleeve, Classic self-collar, 4-way stretch capabilities',
    'quantity': '75',
    'productTitle': "Walter Hagen Men's Perfect 11 Novelty Print Golf Polo",
    'brand': 'Walter Hagen'
}, {
    'gender': 'Men',
    'productLocation': 'right corner of the first floor',
    'productCategory': 'Apparel',
    'productId': 'p10123',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'colour': 'Pink',
    'productType': 'Shirts',
    'productSize': 'Large',
    'image': '21WHGMP11JSMNPRNTAPT_Jasmine_Pink_Cream-1.webp',
    'price': '8',
    'productFeatures': 'Regular, Classic self-collar',
    'quantity': '70',
    'productTitle': "Walter Hagen Men's Perfect 11 Novelty Print Golf Polo",
    'brand': 'Walter Hagen'
}, {
    'gender': 'Men',
    'productLocation': 'right corner of the first floor',
    'productCategory': 'Apparel',
    'productId': 'p10124',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Blue',
    'productType': 'Shirts',
    'productSize': 'Large',
    'image': '19WHGMP11CHMPNSHPAPT_Blue_Wave_White-1.webp',
    'price': '9',
    'productFeatures': 't-shirt',
    'quantity': '59',
    'productTitle': "Walter Hagen Men's Perfect 11 Majors Championship Stripe Golf Polo",
    'brand': 'Walter Hagen'
}, {
    'gender': 'Men',
    'productLocation': 'right corner of the first floor',
    'productCategory': 'Apparel',
    'productId': 'p10125',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'colour': 'Red',
    'productType': 'Shirts',
    'productSize': 'Large',
    'image': '21CTTMMLSFTHWFLNLCAS_Mineral_Red.jfif',
    'price': '49',
    'productFeatures': 'Regular, Garment washed',
    'quantity': '179',
    'productTitle': "Carhartt Men's Loose Fit Heavyweight Long Sleeve Flannel Plaid Shirt",
    'brand': 'Carhartt'
}, {
    'gender': 'Men',
    'productLocation': 'left corner of the store on the first floor',
    'productCategory': 'Apparel',
    'productId': 'p10126',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'colour': 'Grey',
    'productType': 'Shirts',
    'productSize': 'Medium',
    'image': '22CMBMDRFTGDWVNLSAOT_City_Grey.webp',
    'price': '60',
    'productFeatures': 'Cuffed sleeves, Two button snap chest pockets',
    'quantity': '2',
    'productTitle': "Columbia Men's Drift Guide Woven Long Sleeve Shirt",
    'brand': 'Columbia'
}, {
    'gender': 'Men',
    'productLocation': 'middle of the store at the first floor ',
    'productCategory': 'Apparel',
    'productId': 'p10127',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'colour': 'Brown',
    'productType': 'Shirts',
    'productSize': 'Small',
    'image': '21CTTMRLXFTFLNLSHCAS_Carhartt_Brown.webp',
    'price': '79',
    'productFeatures': 'Relaxed, Triple-stitched, Interior chest pocket',
    'quantity': '54',
    'productTitle': "Carhartt Men's Relaxed Fit Heavyweight Flannel Sherpa Lined Shirt ",
    'brand': 'Carhartt'
}, {
    'gender': 'Men',
    'productLocation': 'left corner of the store on the first floor',
    'productCategory': 'Apparel',
    'productId': 'p10128',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'colour': 'Brown',
    'productType': 'Shirts',
    'productSize': 'Medium',
    'image': '21CTTMMRDRLXDFTHWCAS_Brown.webp',
    'price': '89',
    'productFeatures': 'Relaxed, Spacious 3-piece hoodies,Jacket',
    'quantity': '34',
    'productTitle': "Carhartt Men's Rain Defender Relaxed Fit Heavyweight Hooded Shirt Jacket",
    'brand': 'Carhartt'
}, {
    'gender': 'Men',
    'productLocation': 'left corner of the store on the first floor',
    'productCategory': 'Apparel',
    'productId': 'p10129',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'colour': 'Blue',
    'productType': 'Shirts',
    'productSize': 'Medium',
    'image': '22CTTMMRLXDFTDNMLMOU_Blue.jfif',
    'price': '79',
    'productFeatures': 'Blanket lining, Adjustable cuffs,Relaxed,Jacket',
    'quantity': '1',
    'productTitle': "Carhartt Men's Relaxed Fit Denim Lined Snap Shirt Jacket",
    'brand': 'Carhartt'
}, {
    'gender': 'Men',
    'productLocation': 'left corner of the store on the first floor',
    'productCategory': 'Apparel',
    'productId': 'p10130',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'colour': 'Blue',
    'productType': 'Shirts',
    'productSize': 'Medium',
    'image': '22CTTMMRLXDFTDNMLMOUA_Blue.webp',
    'price': '89',
    'productFeatures': 'Relaxed, Adjustable cuffs,Jacket',
    'quantity': '1',
    'productTitle': "Carhartt Men's Relaxed Fit Denim Lined Snap Shirt Jacket â€“ Big & Tall",
    'brand': 'Carhartt'
}, {
    'gender': 'Men',
    'productLocation': 'middle of the store at the first floor ',
    'productCategory': 'Apparel',
    'productId': 'p10131',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'colour': 'White',
    'productType': 'Shirts',
    'productSize': 'Small',
    'image': '21TNOMMRRYLWFLNNLAPT_White.webp',
    'price': '75',
    'productFeatures': 'Standard, Lightweight',
    'quantity': '41',
    'productTitle': "The North Face Men's Arroyo Lightweight Flannel Shirt",
    'brand': 'North Face'
}, {
    'gender': 'Men',
    'productLocation': 'middle of the store at the first floor ',
    'productCategory': 'Apparel',
    'productId': 'p10132',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'colour': 'Pink',
    'productType': 'Shirts',
    'productSize': 'Small',
    'image': '21AQ3MMDBRSHDFLNNAPT_PINK.webp',
    'price': '20',
    'productFeatures': 'Standard, long sleeves,t-shirt',
    'quantity': '134',
    'productTitle': "Alpine Design Men's Brushed Flannel Long Sleeve Shirt",
    'brand': 'Alpine Design'
}, {
    'gender': 'Men',
    'productLocation': 'middle of the store at the first floor ',
    'productCategory': 'Apparel',
    'productId': 'p10133',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'colour': 'Black',
    'productType': 'Shirts',
    'productSize': 'Small',
    'image': '21TM1MTCHGBTTNPLSMGA_Black.jfif',
    'price': '134',
    'productFeatures': 'Regular, double-weave fabric, Removable collar',
    'quantity': '1',
    'productTitle': "TravisMathew Men's Touch And Go Button-Up Flannel Golf Shirt",
    'brand': 'TravisMathew'
}, {
    'gender': 'Men',
    'productLocation': ' right corner of the Second floor',
    'productCategory': 'Apparel',
    'productId': 'p10134',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'colour': 'Green',
    'productType': 'Shirts',
    'productSize': 'XL',
    'image': '22CTTMMLSFTHWFLNLMOA_Green.webp',
    'price': '49',
    'productFeatures': 'Triple-stitched, Two-button adjustable cuffs, Button front closure, Loose',
    'quantity': '4',
    'productTitle': "Carhartt Men's Loose Fit Flannel Long Sleeve Plaid Shirt",
    'brand': 'Carhartt'
}, {
    'gender': 'Men',
    'productLocation': ' right corner of the Second floor',
    'productCategory': 'Apparel',
    'productId': 'p10135',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'colour': 'White',
    'productType': 'Shirts',
    'productSize': 'XL',
    'image': '20CMBMMRPDRVRSPRNAPT_White.webp',
    'price': '17',
    'productFeatures': 'Classic silhouette, Half sleeves',
    'quantity': '26',
    'productTitle': "Columbia Men's Rapid Rivers Printed Short Sleeve Shirt",
    'brand': 'Columbia'
}, {
    'gender': 'Men',
    'productLocation': ' right corner of the Second floor',
    'productCategory': 'Apparel',
    'productId': 'p10136',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Blue',
    'productType': 'Shirts',
    'productSize': 'XL',
    'image': '21HRLMSTRTCHPRNTXAPT_Blue.webp',
    'price': '52',
    'productFeatures': 'Relaxed, stylish prints',
    'quantity': '10',
    'productTitle': "Hurley Men's One and Only Stretch Print Button Down Shirt",
    'brand': 'Hurley'
}, {
    'gender': 'Men',
    'productLocation': ' right corner of the Second floor',
    'productCategory': 'Apparel',
    'productId': 'p10137',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Black',
    'productType': 'Shirts',
    'productSize': 'XL',
    'image': '18TM1MQNLLLSWVNF1APT_Black.webp',
    'price': '129',
    'productFeatures': 'Regular, Removable collar, Button-up',
    'quantity': '1',
    'productTitle': "TravisMathew Men's Quinella Long Sleeve Golf Shirt",
    'brand': 'TravisMathew'
}, {
    'gender': 'Men',
    'productLocation': 'left corner of the store at the Second floor ',
    'productCategory': 'Apparel',
    'productId': 'p10138',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Black',
    'productType': 'Shirts',
    'productSize': 'XXL',
    'image': '21TM1MSTKSBTTNPLSMGA_Black.webp',
    'price': '124',
    'productFeatures': 'Regular, Light weight',
    'quantity': '1',
    'productTitle': "TravisMathew Men's High Stakes Button-Up Flannel Golf Shirt",
    'brand': 'TravisMathew'
}, {
    'gender': 'Men',
    'productLocation': 'last left corner of the store',
    'productCategory': 'Apparel',
    'productId': 'p10139',
    'isToprated': 'TRUE',
    'isBestSeller': 'TRUE',
    'colour': 'Cream',
    'productType': 'Pants',
    'productSize': 'Large',
    'image': '21KRMMCMMTR5PCKTSMPD_Sandy_Clay-1.webp',
    'price': '80',
    'productFeatures': 'Skinny, 5 pockets,Durable, bonded belt loops',
    'quantity': '29',
    'productTitle': "VRST Men's Limitless 5 Pocket Skinny Fit Pant",
    'brand': 'VRST'
}, {
    'gender': 'Men',
    'productLocation': 'last left corner of the store',
    'productCategory': 'Apparel',
    'productId': 'p10140',
    'isToprated': 'TRUE',
    'isBestSeller': 'FALSE',
    'colour': 'Blue',
    'productType': 'Pants',
    'productSize': 'Large',
    'image': '21KRMMSLMFTPNTXXXMPD_DarkerBlue_Ardosia_Slate.webp',
    'price': '80',
    'productFeatures': 'activewear, Stretch fabric,Slim',
    'quantity': '17',
    'productTitle': "VRST Men's Limitless Slant Pocket Slim Fit Pants",
    'brand': 'VRST'
}, {
    'gender': 'Men',
    'productLocation': 'last left corner of the store',
    'productCategory': 'Apparel',
    'productId': 'p10141',
    'isToprated': 'FALSE',
    'isBestSeller': 'TRUE',
    'colour': 'Brown',
    'productType': 'Pants',
    'productSize': 'Large',
    'image': '21KRMMTHLTCFTPNTXMPD_Delta_Brown.webp',
    'price': '80',
    'productFeatures': 'Athletic pant, Stretch-constructed,Bonded belt loops,athlete',
    'quantity': '59',
    'productTitle': "VRST Men's Limitless Slant Pocket Athletic Fit Pants",
    'brand': 'VRST'
}, {
    'gender': 'Men',
    'productLocation': 'last right corner of the store',
    'productCategory': 'Apparel',
    'productId': 'p10142',
    'isToprated': 'FALSE',
    'isBestSeller': 'FALSE',
    'colour': 'Orange',
    'productType': 'Pants',
    'productSize': 'Medium',
    'image': '22KRMMSYPNTXXXXXXMPD_Orange.webp',
    'price': '40',
    'productFeatures': 'Relaxed, Two zippered back pockets,2-way stretch fabric',
    'quantity': '25',
    'productTitle': "VRST Men's Athletic Fit Easy Pant",
    'brand': 'VRST'
}, {
    'gender': 'Men',
    'productLocation': 'last right corner of the store',
    'productCategory': 'Apparel',
    'productId': 'p10143',
    'isToprated': 'TRUE',
    'isBestSeller': 'TRUE',
    'colour': 'Black',
    'productType': 'Pants',
    'productSize': 'Medium',
    'image': '20TM1MLGCYSP20XXXMGAAX_Black.webp',
    'price': '159',
    'productFeatures': 'Regular, Lightweight cotton, Stretch waistband',
    'quantity': '30',
    'productTitle': "TravisMathew Men's Legacy Denim Golf Pants",
    'brand': 'TravisMathew'
}, {
    'productLocation': ' Right corner on the Second Floor.',
    'productCategory': 'Apparel',
    'productId': 'p10144',
    'isToprated': 'TRUE',
    'isBestSeller': 'TRUE',
    'colour': 'Black',
    'productType': 'Backpacks',
    'productSize': 'Medium',
    'image': '20TM1MLGCYSP20XXXMGAAX_Black.webp',
    'price': '190',
    'productFeatures': 'Regular, Lightweight',
    'quantity': 'NaN',
    'productTitle': 'American Tourister',
    'brand': 'American Tourister'
}]

data = {
    "data":"djfhuhf",
    "data1":"fhldhflsdjhlsdhosdlkfhlsd"
}

var enumObj = {};
enumObj["brands"] = convertToEnumObj(data.map((item)=>item.brand));
enumObj["productSize"] = convertToEnumObj(data.map((item)=>item.productSize));
enumObj["productType"] = convertToEnumObj(data.map((item)=>item.productType));
enumObj["productColour"] = convertToEnumObj(data.map((item)=>item.colour));
enumObj["productId"] = convertToEnumObj(data.map((item)=>item.productId));


